// <auto-generated />
namespace HXCloud.Repository.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201803280354427_updateProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
