// <auto-generated />
namespace HXCloud.Repository.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addmenu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmenu));
        
        string IMigrationMetadata.Id
        {
            get { return "201803290322213_addmenu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
